 ---
title: "Applying an Equity Lens to Patient Safety"
author: "Maggie Zhai"
format: pdf
editor: visual
---

```{r}
#| echo: false
#| output: false
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(readxl)
library(janitor)
```

# Overview

```{r}
# load and clean data
sex <- read_excel(path = "applying-equity-lens-patient-safety-data-tables-en.xlsx", 
                    sheet = 7,
                    range = cell_rows(2:407),
                    guess_max = 1048576) |> clean_names()

age <- read_excel(path = "applying-equity-lens-patient-safety-data-tables-en.xlsx", 
                    sheet = 8,
                    range = cell_rows(2:2432),
                    guess_max = 1048576) |> clean_names()

income <- read_excel(path = "applying-equity-lens-patient-safety-data-tables-en.xlsx", 
                    sheet = 9,
                    range = cell_rows(2:2027),
                    guess_max = 1048576)|> clean_names()

geography <- read_excel(path = "applying-equity-lens-patient-safety-data-tables-en.xlsx", 
                    sheet = 10,
                    range = cell_rows(2:812),
                    guess_max = 1048576)|> clean_names()
```

```{r echo = T, fig.width=12, fig.height=7}
# rates over time
sex_dat <- sex |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  filter(hospital_harm_category != "Overall") |>
  filter(patient_profile == "All patients") |>
  select(patient_profile, fiscal_year, hospital_harm_category, recorded_sex_or_gender,
         crude_rate_per_100_hospitalizations)

p <- ggplot(sex_dat, aes(x = fiscal_year, y = crude_rate_per_100_hospitalizations, 
                    group = hospital_harm_category, color = hospital_harm_category)) +
  geom_line(color = "grey") +
  geom_point(aes(color = hospital_harm_category)) 

p + labs(colour = "Hospital Harm Category") +
  xlab("Year") +
  ylab("Rate per 100 hospitalizations") +
  theme(legend.position = "bottom")
```

# Geographical Disparities

```{r echo = T, fig.width=12, fig.height=7}
# mean rates of urban vs rural regions by hospital harm category
geo_plot <- geography |>  
  filter(hospital_harm_category != "Overall") |>
  filter(patient_profile == "All patients") |>
  select(urban_versus_rural_remote_geography, hospital_harm_category, crude_rate_per_100_hospitalizations) |>
  group_by(urban_versus_rural_remote_geography, hospital_harm_category) |>
  summarise(mean_crude_rate = mean(crude_rate_per_100_hospitalizations), .groups = "drop")

ggplot(geo_plot, aes(x = hospital_harm_category, y = mean_crude_rate, fill = urban_versus_rural_remote_geography)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Comparison of Hospital Harm Categories by Geography",
       x = "Hospital Harm Category",
       y = "Mean Rate",
       fill = "Geography Type") +
  theme(legend.position = "bottom")
```

```{r}

# split data by category
medication <- geography |>  
  filter(hospital_harm_category == "Health Care–/Medication-Associated Conditions") |>
  filter(patient_profile == "All patients") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  select(urban_versus_rural_remote_geography, crude_rate_per_100_hospitalizations)

infections <- geography |>  
  filter(hospital_harm_category == "Health Care–Associated Infections") |>
  filter(patient_profile == "All patients") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  select(urban_versus_rural_remote_geography, crude_rate_per_100_hospitalizations)

accident <- geography |>  
  filter(hospital_harm_category == "Patient Accidents") |>
  filter(patient_profile == "All patients") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  select(urban_versus_rural_remote_geography, crude_rate_per_100_hospitalizations)

procedure <- geography |>  
  filter(hospital_harm_category == "Procedure-Associated Conditions") |>
  filter(patient_profile == "All patients") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  select(urban_versus_rural_remote_geography, crude_rate_per_100_hospitalizations)

# t tests
t.test(crude_rate_per_100_hospitalizations ~ urban_versus_rural_remote_geography, data = medication)
t.test(crude_rate_per_100_hospitalizations ~ urban_versus_rural_remote_geography, data = infections)
t.test(crude_rate_per_100_hospitalizations ~ urban_versus_rural_remote_geography, data = accident)
t.test(crude_rate_per_100_hospitalizations ~ urban_versus_rural_remote_geography, data = procedure)

```

```{r, fig.height=6, fig.width=10}
p1 <- ggplot(medication, aes(x = crude_rate_per_100_hospitalizations, fill = urban_versus_rural_remote_geography)) +
  geom_density(alpha = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Health Care–/Medication-Associated Conditions",
        x = "Rate", y = "Density") + theme(legend.position = "none")

p2<- ggplot(infections, aes(x = crude_rate_per_100_hospitalizations, fill = urban_versus_rural_remote_geography)) +
  geom_density(alpha = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Health Care–Associated Infections Rates",
        x = "Rate", y = "Density") + theme(legend.position = "none")

p3 <- ggplot(accident, aes(x = crude_rate_per_100_hospitalizations, fill = urban_versus_rural_remote_geography)) +
  geom_density(alpha = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Patient Accidents Rates",
        x = "Rate", y = "Density") + theme(legend.position = "none")

p4 <- ggplot(procedure, aes(x = crude_rate_per_100_hospitalizations, fill = urban_versus_rural_remote_geography)) +
  geom_density(alpha = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Procedure-Associated ConditionsRates",
        x = "Rate", y = "Density") + theme(legend.position = "none")

grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2)
```


# Economical Disparities

```{r}


# split data by category
medication <- income |>  
  filter(hospital_harm_category == "Health Care–/Medication-Associated Conditions") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  filter(patient_profile == "All patients") |>
  select(neighbourhood_income_quintile, crude_rate_per_100_hospitalizations)

infections <- income |>  
  filter(hospital_harm_category == "Health Care–Associated Infections") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  filter(patient_profile == "All patients") |>
  select(neighbourhood_income_quintile, crude_rate_per_100_hospitalizations)

accident <- income |>  
  filter(hospital_harm_category == "Patient Accidents") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  filter(patient_profile == "All patients") |>
  select(neighbourhood_income_quintile, crude_rate_per_100_hospitalizations)

procedure <- income |>  
  filter(hospital_harm_category == "Procedure-Associated Conditions") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  filter(patient_profile == "All patients") |>
  select(neighbourhood_income_quintile, crude_rate_per_100_hospitalizations)


```


```{r, fig.height=6, fig.width=10}
p1 <- ggplot(medication, aes(x = crude_rate_per_100_hospitalizations, fill = neighbourhood_income_quintile)) +
  geom_density(alpha = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Health Care–/Medication-Associated Conditions",
        x = "Rate", y = "Density") + labs(fill = "Neighbourhood Income Quintile") +
   theme(legend.position = "none")
#+ theme(legend.position = "bottom")

p2<- ggplot(infections, aes(x = crude_rate_per_100_hospitalizations, fill = neighbourhood_income_quintile)) +
  geom_density(alpha = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Health Care–Associated Infections Rates",
        x = "Rate", y = "Density") + theme(legend.position = "none")

p3 <- ggplot(accident, aes(x = crude_rate_per_100_hospitalizations, fill = neighbourhood_income_quintile)) +
  geom_density(alpha = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Patient Accidents Rates",
        x = "Rate", y = "Density") + theme(legend.position = "none")

p4 <- ggplot(procedure, aes(x = crude_rate_per_100_hospitalizations, fill = neighbourhood_income_quintile)) +
  geom_density(alpha = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Procedure-Associated Conditions Rates",
        x = "Rate", y = "Density") + theme(legend.position = "none")

grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2)
```



```{r}
income_reduced <- income |>  
  filter(hospital_harm_category != "Overall") |>
  filter(recorded_sex_or_gender == "Both males and females") |>
  filter(patient_profile == "All patients")

income_reduced$hospital_harm_category <- factor(income_reduced$hospital_harm_category, levels = c("Patient Accidents", "Health Care–/Medication-Associated Conditions", "Health Care–Associated Infections", "Procedure-Associated Conditions"))

fit <- lm(crude_rate_per_100_hospitalizations ~ neighbourhood_income_quintile + hospital_harm_category, data = income_reduced)
summary(fit)

# check MLR assumptions
# par(mfrow = c(1,3), pty = "s")
# plot(fit, which=c(1,2,3))

```


